apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: analytics:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
