apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: microservice
spec:
  selector:
    app: analytics
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
