apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: texto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:stable
          ports:
            - containerPort: 80
