apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: texto-app
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30081
