apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: database
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      initContainers:
        - name: create-log-dir
          image: busybox:latest
          command: ["sh", "-c", "mkdir -p /data/logs && chmod 777 /data/logs"]
          volumeMounts:
            - name: logs-data
              mountPath: /data
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.16-debian-1
          volumeMounts:
            - name: logs-data
              mountPath: /data
            - name: varlog
              mountPath: /var/log/containers
            - name: fluentd-config
              mountPath: /fluentd/etc
          command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf"]
      volumes:
        - name: logs-data
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: varlog
          hostPath:
            path: /var/log/containers
            type: Directory
        - name: fluentd-config
          configMap:
            name: fluentd-config
