apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: texto-app
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.16-debian-1
          ports:
            - containerPort: 24224
