apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: database
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /tmp/fluentd-containers.log.pos
      tag kube.*
      <parse>
        @type json
      </parse>
    </source>

    <match **>
      @type stdout
    </match>
