apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: database
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kube.*
      format json
    </source>

    <match **>
      @type file
      path /data/logs/all-logs.log
      append true
    </match>
