apiVersion: apps/v1
kind: Deployment
metadata:
  name: keywords
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keywords
  template:
    metadata:
      labels:
        app: keywords
    spec:
      containers:
        - name: keywords
          image: keywords:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
