apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: texto-app
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
