apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: database
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
