apiVersion: v1
kind: Service
metadata:
  name: summary-service
  namespace: microservice
spec:
  selector:
    app: summary
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
