apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: microservice
spec:
  selector:
    app: translation
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
