apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: texto-app
spec:
  selector:
    app: translation
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
