apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation
  template:
    metadata:
      labels:
        app: translation
    spec:
      containers:
        - name: translation
          image: translation:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
